[metadata]
addr = 4196125
size = 184
last_change = 1659469235

[stack_vars.-28]
last_change = 1659469235
stack_offset = -40
stack_offset_type = 1
name = "my_buf1"
type = "char[16]"
size = 16
addr = 4196125
