[metadata]
addr = 4196125
size = 184
last_change = 1659468887

[stack_vars.-28]
last_change = 1659468866
stack_offset = -40
stack_offset_type = 1
name = "my_buf1"
type = "char[16]"
size = 16
addr = 4196125

[stack_vars.-18]
last_change = 1659468873
stack_offset = -24
stack_offset_type = 1
name = "my_buf2"
type = "char[16]"
size = 16
addr = 4196125

[stack_vars.-2c]
last_change = 1659468887
stack_offset = -44
stack_offset_type = 1
name = "buf"
type = "int"
size = 4
addr = 4196125
