[metadata]
addr = 4196125
size = 184
last_change = 1659473169

[stack_vars.-2c]
last_change = 1659473169
stack_offset = -44
stack_offset_type = 1
name = "variable4"
type = "int"
size = 4
addr = 4196125
